version: 1
config:
  - type: physical
    name: interface0
    mac_address: {{ .MACAddress }}
    subnets:
      - type: static
        address: {{ .IPAddress }}/{{ .Netmask }}
        gateway: {{ .Gateway }}
        dns_nameservers:
          - 8.8.8.8
          - 8.8.4.4
