#cloud-config
package_update: true
package_upgrade: true

users:
  - name: sysadmin
    ssh-authorized-keys:
      - {{ .SSHKey}}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

hostname: {{ .Hostname }}
manage_etc_hosts: localhost
